version: "3.8"
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/shopping_store?sslmode=disable
    restart: always
    depends_on:
      - postgres
    links:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:15.2
    ports:
      - "5434:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=shopping_store
    restart: always

volumes:
  postgres: