// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package shopping_store

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ShoppingStoreClient is the client API for ShoppingStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShoppingStoreClient interface {
	AddStaff(ctx context.Context, in *AddStaffRequest, opts ...grpc.CallOption) (*AddStaffResponse, error)
}

type shoppingStoreClient struct {
	cc grpc.ClientConnInterface
}

func NewShoppingStoreClient(cc grpc.ClientConnInterface) ShoppingStoreClient {
	return &shoppingStoreClient{cc}
}

func (c *shoppingStoreClient) AddStaff(ctx context.Context, in *AddStaffRequest, opts ...grpc.CallOption) (*AddStaffResponse, error) {
	out := new(AddStaffResponse)
	err := c.cc.Invoke(ctx, "/shopping_store.ShoppingStore/AddStaff", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShoppingStoreServer is the server API for ShoppingStore service.
// All implementations must embed UnimplementedShoppingStoreServer
// for forward compatibility
type ShoppingStoreServer interface {
	AddStaff(context.Context, *AddStaffRequest) (*AddStaffResponse, error)
	mustEmbedUnimplementedShoppingStoreServer()
}

// UnimplementedShoppingStoreServer must be embedded to have forward compatible implementations.
type UnimplementedShoppingStoreServer struct {
}

func (UnimplementedShoppingStoreServer) AddStaff(context.Context, *AddStaffRequest) (*AddStaffResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddStaff not implemented")
}
func (UnimplementedShoppingStoreServer) mustEmbedUnimplementedShoppingStoreServer() {}

// UnsafeShoppingStoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShoppingStoreServer will
// result in compilation errors.
type UnsafeShoppingStoreServer interface {
	mustEmbedUnimplementedShoppingStoreServer()
}

func RegisterShoppingStoreServer(s grpc.ServiceRegistrar, srv ShoppingStoreServer) {
	s.RegisterService(&ShoppingStore_ServiceDesc, srv)
}

func _ShoppingStore_AddStaff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddStaffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShoppingStoreServer).AddStaff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shopping_store.ShoppingStore/AddStaff",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShoppingStoreServer).AddStaff(ctx, req.(*AddStaffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ShoppingStore_ServiceDesc is the grpc.ServiceDesc for ShoppingStore service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShoppingStore_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shopping_store.ShoppingStore",
	HandlerType: (*ShoppingStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddStaff",
			Handler:    _ShoppingStore_AddStaff_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shopping_store.proto",
}
