// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.12
// source: shopping_store_v2.proto

package shopping_store_v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Staff struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StaffId int64 `protobuf:"varint,2,opt,name=staff_id,json=staffId,proto3" json:"staff_id,omitempty"`
	Count   int32 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *Staff) Reset() {
	*x = Staff{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shopping_store_v2_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Staff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Staff) ProtoMessage() {}

func (x *Staff) ProtoReflect() protoreflect.Message {
	mi := &file_shopping_store_v2_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Staff.ProtoReflect.Descriptor instead.
func (*Staff) Descriptor() ([]byte, []int) {
	return file_shopping_store_v2_proto_rawDescGZIP(), []int{0}
}

func (x *Staff) GetStaffId() int64 {
	if x != nil {
		return x.StaffId
	}
	return 0
}

func (x *Staff) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type AddStaffRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Staff  *Staff `protobuf:"bytes,2,opt,name=staff,proto3" json:"staff,omitempty"`
}

func (x *AddStaffRequest) Reset() {
	*x = AddStaffRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shopping_store_v2_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddStaffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddStaffRequest) ProtoMessage() {}

func (x *AddStaffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shopping_store_v2_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddStaffRequest.ProtoReflect.Descriptor instead.
func (*AddStaffRequest) Descriptor() ([]byte, []int) {
	return file_shopping_store_v2_proto_rawDescGZIP(), []int{1}
}

func (x *AddStaffRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddStaffRequest) GetStaff() *Staff {
	if x != nil {
		return x.Staff
	}
	return nil
}

type AddStaffResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Staff *Staff `protobuf:"bytes,1,opt,name=staff,proto3" json:"staff,omitempty"`
}

func (x *AddStaffResponse) Reset() {
	*x = AddStaffResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shopping_store_v2_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddStaffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddStaffResponse) ProtoMessage() {}

func (x *AddStaffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shopping_store_v2_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddStaffResponse.ProtoReflect.Descriptor instead.
func (*AddStaffResponse) Descriptor() ([]byte, []int) {
	return file_shopping_store_v2_proto_rawDescGZIP(), []int{2}
}

func (x *AddStaffResponse) GetStaff() *Staff {
	if x != nil {
		return x.Staff
	}
	return nil
}

type RemoveStaffRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StaffId int64 `protobuf:"varint,2,opt,name=staff_id,json=staffId,proto3" json:"staff_id,omitempty"`
}

func (x *RemoveStaffRequest) Reset() {
	*x = RemoveStaffRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shopping_store_v2_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveStaffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveStaffRequest) ProtoMessage() {}

func (x *RemoveStaffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shopping_store_v2_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveStaffRequest.ProtoReflect.Descriptor instead.
func (*RemoveStaffRequest) Descriptor() ([]byte, []int) {
	return file_shopping_store_v2_proto_rawDescGZIP(), []int{3}
}

func (x *RemoveStaffRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RemoveStaffRequest) GetStaffId() int64 {
	if x != nil {
		return x.StaffId
	}
	return 0
}

type RemoveStaffResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RemoveStaffResponse) Reset() {
	*x = RemoveStaffResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shopping_store_v2_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveStaffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveStaffResponse) ProtoMessage() {}

func (x *RemoveStaffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shopping_store_v2_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveStaffResponse.ProtoReflect.Descriptor instead.
func (*RemoveStaffResponse) Descriptor() ([]byte, []int) {
	return file_shopping_store_v2_proto_rawDescGZIP(), []int{4}
}

type GetUserStaffRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetUserStaffRequest) Reset() {
	*x = GetUserStaffRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shopping_store_v2_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserStaffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserStaffRequest) ProtoMessage() {}

func (x *GetUserStaffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shopping_store_v2_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserStaffRequest.ProtoReflect.Descriptor instead.
func (*GetUserStaffRequest) Descriptor() ([]byte, []int) {
	return file_shopping_store_v2_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserStaffRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserStaffResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Store []*Staff `protobuf:"bytes,1,rep,name=store,proto3" json:"store,omitempty"`
}

func (x *GetUserStaffResponse) Reset() {
	*x = GetUserStaffResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shopping_store_v2_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserStaffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserStaffResponse) ProtoMessage() {}

func (x *GetUserStaffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shopping_store_v2_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserStaffResponse.ProtoReflect.Descriptor instead.
func (*GetUserStaffResponse) Descriptor() ([]byte, []int) {
	return file_shopping_store_v2_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserStaffResponse) GetStore() []*Staff {
	if x != nil {
		return x.Store
	}
	return nil
}

type UpdateStaffCountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Staff  *Staff `protobuf:"bytes,2,opt,name=staff,proto3" json:"staff,omitempty"`
}

func (x *UpdateStaffCountRequest) Reset() {
	*x = UpdateStaffCountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shopping_store_v2_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateStaffCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStaffCountRequest) ProtoMessage() {}

func (x *UpdateStaffCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shopping_store_v2_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStaffCountRequest.ProtoReflect.Descriptor instead.
func (*UpdateStaffCountRequest) Descriptor() ([]byte, []int) {
	return file_shopping_store_v2_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateStaffCountRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateStaffCountRequest) GetStaff() *Staff {
	if x != nil {
		return x.Staff
	}
	return nil
}

type UpdateStaffCountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Staff *Staff `protobuf:"bytes,1,opt,name=staff,proto3" json:"staff,omitempty"`
}

func (x *UpdateStaffCountResponse) Reset() {
	*x = UpdateStaffCountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shopping_store_v2_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateStaffCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStaffCountResponse) ProtoMessage() {}

func (x *UpdateStaffCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shopping_store_v2_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStaffCountResponse.ProtoReflect.Descriptor instead.
func (*UpdateStaffCountResponse) Descriptor() ([]byte, []int) {
	return file_shopping_store_v2_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateStaffCountResponse) GetStaff() *Staff {
	if x != nil {
		return x.Staff
	}
	return nil
}

var File_shopping_store_v2_proto protoreflect.FileDescriptor

var file_shopping_store_v2_proto_rawDesc = []byte{
	0x0a, 0x17, 0x73, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x65,
	0x5f, 0x76, 0x32, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x73, 0x68, 0x6f, 0x70, 0x70,
	0x69, 0x6e, 0x67, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x76, 0x32, 0x22, 0x38, 0x0a, 0x05,
	0x53, 0x74, 0x61, 0x66, 0x66, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x74, 0x61, 0x66, 0x66, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x73, 0x74, 0x61, 0x66, 0x66, 0x49, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x5a, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x53, 0x74, 0x61,
	0x66, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x2e, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x66, 0x66, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x73, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x74, 0x6f,
	0x72, 0x65, 0x5f, 0x76, 0x32, 0x2e, 0x53, 0x74, 0x61, 0x66, 0x66, 0x52, 0x05, 0x73, 0x74, 0x61,
	0x66, 0x66, 0x22, 0x42, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x53, 0x74, 0x61, 0x66, 0x66, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x66, 0x66, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x73, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67,
	0x5f, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x76, 0x32, 0x2e, 0x53, 0x74, 0x61, 0x66, 0x66, 0x52,
	0x05, 0x73, 0x74, 0x61, 0x66, 0x66, 0x22, 0x48, 0x0a, 0x12, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x53, 0x74, 0x61, 0x66, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x74, 0x61, 0x66, 0x66, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x73, 0x74, 0x61, 0x66, 0x66, 0x49, 0x64,
	0x22, 0x15, 0x0a, 0x13, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x74, 0x61, 0x66, 0x66, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2e, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x53, 0x74, 0x61, 0x66, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x46, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x53, 0x74, 0x61, 0x66, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x2e, 0x0a, 0x05, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18,
	0x2e, 0x73, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f,
	0x76, 0x32, 0x2e, 0x53, 0x74, 0x61, 0x66, 0x66, 0x52, 0x05, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x22,
	0x62, 0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x66, 0x66, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x2e, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x66, 0x66, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x73, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x74,
	0x6f, 0x72, 0x65, 0x5f, 0x76, 0x32, 0x2e, 0x53, 0x74, 0x61, 0x66, 0x66, 0x52, 0x05, 0x73, 0x74,
	0x61, 0x66, 0x66, 0x22, 0x4a, 0x0a, 0x18, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61,
	0x66, 0x66, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x2e, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x66, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18,
	0x2e, 0x73, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f,
	0x76, 0x32, 0x2e, 0x53, 0x74, 0x61, 0x66, 0x66, 0x52, 0x05, 0x73, 0x74, 0x61, 0x66, 0x66, 0x32,
	0x68, 0x0a, 0x0f, 0x53, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x6f, 0x72, 0x65,
	0x56, 0x32, 0x12, 0x55, 0x0a, 0x08, 0x41, 0x64, 0x64, 0x53, 0x74, 0x61, 0x66, 0x66, 0x12, 0x22,
	0x2e, 0x73, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f,
	0x76, 0x32, 0x2e, 0x41, 0x64, 0x64, 0x53, 0x74, 0x61, 0x66, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x23, 0x2e, 0x73, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x74,
	0x6f, 0x72, 0x65, 0x5f, 0x76, 0x32, 0x2e, 0x41, 0x64, 0x64, 0x53, 0x74, 0x61, 0x66, 0x66, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x2d, 0x5a, 0x2b, 0x70, 0x6b, 0x67,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x74,
	0x6f, 0x72, 0x65, 0x5f, 0x76, 0x32, 0x3b, 0x73, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x5f,
	0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x76, 0x32, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_shopping_store_v2_proto_rawDescOnce sync.Once
	file_shopping_store_v2_proto_rawDescData = file_shopping_store_v2_proto_rawDesc
)

func file_shopping_store_v2_proto_rawDescGZIP() []byte {
	file_shopping_store_v2_proto_rawDescOnce.Do(func() {
		file_shopping_store_v2_proto_rawDescData = protoimpl.X.CompressGZIP(file_shopping_store_v2_proto_rawDescData)
	})
	return file_shopping_store_v2_proto_rawDescData
}

var file_shopping_store_v2_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_shopping_store_v2_proto_goTypes = []interface{}{
	(*Staff)(nil),                    // 0: shopping_store_v2.Staff
	(*AddStaffRequest)(nil),          // 1: shopping_store_v2.AddStaffRequest
	(*AddStaffResponse)(nil),         // 2: shopping_store_v2.AddStaffResponse
	(*RemoveStaffRequest)(nil),       // 3: shopping_store_v2.RemoveStaffRequest
	(*RemoveStaffResponse)(nil),      // 4: shopping_store_v2.RemoveStaffResponse
	(*GetUserStaffRequest)(nil),      // 5: shopping_store_v2.GetUserStaffRequest
	(*GetUserStaffResponse)(nil),     // 6: shopping_store_v2.GetUserStaffResponse
	(*UpdateStaffCountRequest)(nil),  // 7: shopping_store_v2.UpdateStaffCountRequest
	(*UpdateStaffCountResponse)(nil), // 8: shopping_store_v2.UpdateStaffCountResponse
}
var file_shopping_store_v2_proto_depIdxs = []int32{
	0, // 0: shopping_store_v2.AddStaffRequest.staff:type_name -> shopping_store_v2.Staff
	0, // 1: shopping_store_v2.AddStaffResponse.staff:type_name -> shopping_store_v2.Staff
	0, // 2: shopping_store_v2.GetUserStaffResponse.store:type_name -> shopping_store_v2.Staff
	0, // 3: shopping_store_v2.UpdateStaffCountRequest.staff:type_name -> shopping_store_v2.Staff
	0, // 4: shopping_store_v2.UpdateStaffCountResponse.staff:type_name -> shopping_store_v2.Staff
	1, // 5: shopping_store_v2.ShoppingStoreV2.AddStaff:input_type -> shopping_store_v2.AddStaffRequest
	2, // 6: shopping_store_v2.ShoppingStoreV2.AddStaff:output_type -> shopping_store_v2.AddStaffResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_shopping_store_v2_proto_init() }
func file_shopping_store_v2_proto_init() {
	if File_shopping_store_v2_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_shopping_store_v2_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Staff); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shopping_store_v2_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddStaffRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shopping_store_v2_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddStaffResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shopping_store_v2_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveStaffRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shopping_store_v2_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveStaffResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shopping_store_v2_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserStaffRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shopping_store_v2_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserStaffResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shopping_store_v2_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateStaffCountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shopping_store_v2_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateStaffCountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_shopping_store_v2_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shopping_store_v2_proto_goTypes,
		DependencyIndexes: file_shopping_store_v2_proto_depIdxs,
		MessageInfos:      file_shopping_store_v2_proto_msgTypes,
	}.Build()
	File_shopping_store_v2_proto = out.File
	file_shopping_store_v2_proto_rawDesc = nil
	file_shopping_store_v2_proto_goTypes = nil
	file_shopping_store_v2_proto_depIdxs = nil
}
