// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package shopping_store_v3

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ShoppingStoreV3Client is the client API for ShoppingStoreV3 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShoppingStoreV3Client interface {
	AddStaff(ctx context.Context, in *AddStaffRequest, opts ...grpc.CallOption) (*AddStaffResponse, error)
}

type shoppingStoreV3Client struct {
	cc grpc.ClientConnInterface
}

func NewShoppingStoreV3Client(cc grpc.ClientConnInterface) ShoppingStoreV3Client {
	return &shoppingStoreV3Client{cc}
}

func (c *shoppingStoreV3Client) AddStaff(ctx context.Context, in *AddStaffRequest, opts ...grpc.CallOption) (*AddStaffResponse, error) {
	out := new(AddStaffResponse)
	err := c.cc.Invoke(ctx, "/shopping_store_v3.ShoppingStoreV3/AddStaff", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShoppingStoreV3Server is the server API for ShoppingStoreV3 service.
// All implementations must embed UnimplementedShoppingStoreV3Server
// for forward compatibility
type ShoppingStoreV3Server interface {
	AddStaff(context.Context, *AddStaffRequest) (*AddStaffResponse, error)
	mustEmbedUnimplementedShoppingStoreV3Server()
}

// UnimplementedShoppingStoreV3Server must be embedded to have forward compatible implementations.
type UnimplementedShoppingStoreV3Server struct {
}

func (UnimplementedShoppingStoreV3Server) AddStaff(context.Context, *AddStaffRequest) (*AddStaffResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddStaff not implemented")
}
func (UnimplementedShoppingStoreV3Server) mustEmbedUnimplementedShoppingStoreV3Server() {}

// UnsafeShoppingStoreV3Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShoppingStoreV3Server will
// result in compilation errors.
type UnsafeShoppingStoreV3Server interface {
	mustEmbedUnimplementedShoppingStoreV3Server()
}

func RegisterShoppingStoreV3Server(s grpc.ServiceRegistrar, srv ShoppingStoreV3Server) {
	s.RegisterService(&ShoppingStoreV3_ServiceDesc, srv)
}

func _ShoppingStoreV3_AddStaff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddStaffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShoppingStoreV3Server).AddStaff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shopping_store_v3.ShoppingStoreV3/AddStaff",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShoppingStoreV3Server).AddStaff(ctx, req.(*AddStaffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ShoppingStoreV3_ServiceDesc is the grpc.ServiceDesc for ShoppingStoreV3 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShoppingStoreV3_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shopping_store_v3.ShoppingStoreV3",
	HandlerType: (*ShoppingStoreV3Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddStaff",
			Handler:    _ShoppingStoreV3_AddStaff_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shopping_store_v3.proto",
}
